replicas:
  _default: 1
  dev: 1

selector : dev

name:
  app: pay-helm

service:
  nameApp: pay-helm-service
  portName: helm-pay
  type: NodePort
  port: 80
  targetPort: 8000

kafka:
  portName: port-delivery-kafka
  type: NodePort
  port: 9092
  targetPort: 9092
  bootstrap: kafka:9092

image:
  repository: bobah165/pay
  tag: v20

ingress:
  enabled: false
  name: "pay-service-helm-ingress"
  className: nginx
  host: "arch.homework"
  pathType: Prefix
  path:
    pay: /api/pay
    account: /api/account

db:
  url: jdbc:postgresql://my-db-postgresql:5432/postgres



app:
  db:
    password:
      _default: cG9zdGdyZXM=
    username:
      _default: cG9zdGdyZXM=

