yamlApplicationConfig:
  kafka:
    clusters:
      - name: pay
        bootstrapServers: kafka-broker-0.kafka-broker-headless.default.svc.cluster.local:9092
  auth:
    type: disabled
  management:
    health:
      ldap:
        enabled: false